rss_feeds:
  # Thư viện Quốc gia Việt Nam
  - "https://nlv.gov.vn"
  # Internet Archive (sách tiếng Việt)
  - "https://archive.org/services/collection-rss.php?collection=books&language=Vietnamese"

sitemaps:

